name = "BaseModelica"
uuid = "a17d5099-185d-4ff5-b5d3-51aa4569e56d"
authors = ["jClugstor <jadonclugston@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
